import type { CommandDefinition, JsonObject } from "../../types.js";
import {
  appendArrayQuery,
  clean,
  cmd,
  encStr,
  omit,
  pagingParams,
  param,
  pick,
  salesforgeApi,
} from "../common.js";

type ReqArgs = JsonObject;

export function salesforgeCommands(): CommandDefinition[] {
  return [
    cmd({
      name: "get_me",
      product: "salesforge",
      group: "identity",
      subcommand: "me",
      description: "Validate API key and get current account info.",
      request: () => salesforgeApi("GET", "/me"),
    }),
    cmd({
      name: "list_workspaces",
      product: "salesforge",
      group: "workspaces",
      subcommand: "list",
      description: "List Salesforge workspaces.",
      params: pagingParams,
      request: (a) => salesforgeApi("GET", "/workspaces", { query: pick(a, ["limit", "offset"]) }),
    }),
    cmd({
      name: "create_workspace",
      product: "salesforge",
      group: "workspaces",
      subcommand: "create",
      description: "Create a Salesforge workspace.",
      params: [param("name", "string", true, "Workspace name")],
      request: (a) => salesforgeApi("POST", "/workspaces", { body: pick(a, ["name"]) }),
    }),
    cmd({
      name: "get_workspace",
      product: "salesforge",
      group: "workspaces",
      subcommand: "get",
      description: "Get Salesforge workspace details.",
      params: [param("workspaceId", "string", true, "Workspace ID")],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}`),
    }),
    cmd({
      name: "list_contacts",
      product: "salesforge",
      group: "contacts",
      subcommand: "list",
      description: "List contacts in a workspace with optional filters.",
      params: [
        param("workspaceId", "string", true, "Workspace ID"),
        ...pagingParams,
        param("tagIds", "string", false, "Comma-separated tag IDs"),
        param("validationStatus", "string", false, "Validation status filter"),
      ],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/contacts`, {
        query: pick(a, ["limit", "offset", "tagIds", "validationStatus"]),
      }),
    }),
    cmd({
      name: "create_contact",
      product: "salesforge",
      group: "contacts",
      subcommand: "create",
      description: "Create a contact in a Salesforge workspace.",
      params: [
        param("workspaceId", "string", true, "Workspace ID"),
        param("firstName", "string", true, "First name"),
        param("lastName"),
        param("email"),
        param("company"),
        param("position"),
        param("linkedinUrl"),
        param("tags", "array"),
        param("tagIds", "array"),
        param("customVars", "object"),
      ],
      request: (a) => salesforgeApi("POST", `/workspaces/${encStr(a.workspaceId)}/contacts`, {
        body: omit(a, ["workspaceId"]),
      }),
    }),
    cmd({
      name: "bulk_create_contacts",
      product: "salesforge",
      group: "contacts",
      subcommand: "bulk-create",
      description: "Create up to 100 contacts in a workspace.",
      params: [param("workspaceId", "string", true), param("contacts", "array", true)],
      request: (a) => salesforgeApi("POST", `/workspaces/${encStr(a.workspaceId)}/contacts/bulk`, {
        body: pick(a, ["contacts"]),
      }),
    }),
    cmd({
      name: "get_contact",
      product: "salesforge",
      group: "contacts",
      subcommand: "get",
      description: "Get a contact by ID.",
      params: [param("workspaceId", "string", true), param("contactId", "string", true)],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/contacts/${encStr(a.contactId)}`),
    }),

    // Salesforge: mailboxes, threads, DNC, variables, webhooks
    cmd({
      name: "list_mailboxes",
      product: "salesforge",
      group: "mailboxes",
      subcommand: "list",
      description: "List mailboxes in a Salesforge workspace.",
      params: [param("workspaceId", "string", true), ...pagingParams, param("search"), param("status")],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/mailboxes`, {
        query: pick(a, ["limit", "offset", "search", "status"]),
      }),
    }),
    cmd({
      name: "get_mailbox",
      product: "salesforge",
      group: "mailboxes",
      subcommand: "get",
      description: "Get mailbox details by ID.",
      params: [param("workspaceId", "string", true), param("mailboxId", "string", true)],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/mailboxes/${encStr(a.mailboxId)}`),
    }),
    cmd({
      name: "download_email_attachments",
      product: "salesforge",
      group: "mailboxes",
      subcommand: "download-attachments",
      description: "Download all attachments from an email as base64 ZIP data.",
      params: [param("workspaceId", "string", true), param("mailboxId", "string", true), param("emailId", "string", true)],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/mailboxes/${encStr(a.mailboxId)}/emails/${encStr(a.emailId)}/attachments`, { raw: true }),
    }),
    cmd({
      name: "download_email_attachment",
      product: "salesforge",
      group: "mailboxes",
      subcommand: "download-attachment",
      description: "Download a single email attachment as base64 data.",
      params: [
        param("workspaceId", "string", true),
        param("mailboxId", "string", true),
        param("emailId", "string", true),
        param("contentId", "string", true),
      ],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/mailboxes/${encStr(a.mailboxId)}/emails/${encStr(a.emailId)}/attachments/${encStr(a.contentId)}`, { raw: true }),
    }),
    cmd({
      name: "reply_to_email",
      product: "salesforge",
      group: "mailboxes",
      subcommand: "reply",
      description: "Send a reply to an email thread.",
      params: [
        param("workspaceId", "string", true),
        param("mailboxId", "string", true),
        param("emailId", "string", true),
        param("body", "string", true, "Reply body; HTML supported"),
        param("includeHistory", "boolean"),
        param("cc", "array"),
        param("bcc", "array"),
      ],
      request: (a) => salesforgeApi("POST", `/workspaces/${encStr(a.workspaceId)}/mailboxes/${encStr(a.mailboxId)}/emails/${encStr(a.emailId)}/reply`, {
        body: clean({ content: a.body, includeHistory: a.includeHistory, ccs: a.cc, bccs: a.bcc }),
      }),
    }),
    cmd({
      name: "list_primebox_threads",
      product: "salesforge",
      group: "threads",
      subcommand: "list",
      description: "List primebox threads in a workspace.",
      params: [
        param("workspaceId", "string", true),
        param("positive", "boolean"),
        param("filter"),
        param("labels", "array"),
        param("excludeLabels", "array"),
        param("mailboxIds", "array"),
        param("sequenceIds", "array"),
        param("searchQuery"),
        ...pagingParams,
        param("isUnread", "boolean"),
      ],
      request: (a) => {
        const query = pick(a, ["positive", "filter", "limit", "offset", "isUnread"]);
        if (a.searchQuery !== undefined) query.q = a.searchQuery;
        appendArrayQuery(query, "labels[]", a.labels);
        appendArrayQuery(query, "exclude_labels[]", a.excludeLabels);
        appendArrayQuery(query, "mailbox_ids[]", a.mailboxIds);
        appendArrayQuery(query, "sequence_ids[]", a.sequenceIds);
        return salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/threads`, { query });
      },
    }),
    cmd({
      name: "get_thread",
      product: "salesforge",
      group: "threads",
      subcommand: "get",
      description: "Get full thread details including emails and contact context.",
      params: [param("workspaceId", "string", true), param("mailboxId", "string", true), param("threadId", "string", true)],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/mailboxes/${encStr(a.mailboxId)}/threads/${encStr(a.threadId)}`),
    }),
    cmd({
      name: "list_primebox_labels",
      product: "salesforge",
      group: "threads",
      subcommand: "labels",
      description: "List primebox labels for a workspace.",
      params: [param("workspaceId", "string", true), ...pagingParams],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/primebox-labels`, {
        query: pick(a, ["limit", "offset"]),
      }),
    }),
    cmd({
      name: "update_thread_label",
      product: "salesforge",
      group: "threads",
      subcommand: "label",
      description: "Update the label of a thread.",
      params: [param("workspaceId", "string", true), param("mailboxId", "string", true), param("threadId", "string", true), param("labelId", "string", true)],
      request: (a) => salesforgeApi("PUT", `/workspaces/${encStr(a.workspaceId)}/mailboxes/${encStr(a.mailboxId)}/threads/${encStr(a.threadId)}/label`, {
        body: pick(a, ["labelId"]),
      }),
    }),
    cmd({
      name: "add_dnc_entries",
      product: "salesforge",
      group: "dnc",
      subcommand: "add",
      description: "Add Do-Not-Contact entries to a workspace.",
      params: [param("workspaceId", "string", true), param("dncs", "array", true)],
      request: (a) => salesforgeApi("POST", `/workspaces/${encStr(a.workspaceId)}/dnc/bulk`, { body: pick(a, ["dncs"]) }),
    }),
    cmd({
      name: "list_custom_variables",
      product: "salesforge",
      group: "custom-vars",
      subcommand: "list",
      description: "List custom variables in a workspace.",
      params: [param("workspaceId", "string", true)],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/custom-vars`),
    }),
    cmd({
      name: "list_webhooks",
      product: "salesforge",
      group: "webhooks",
      subcommand: "list",
      description: "List webhooks in a workspace.",
      params: [param("workspaceId", "string", true)],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/integrations/webhooks`),
    }),
    cmd({
      name: "create_webhook",
      product: "salesforge",
      group: "webhooks",
      subcommand: "create",
      description: "Create a webhook in a workspace.",
      params: [param("workspaceId", "string", true), param("name", "string", true), param("url", "string", true), param("type", "string", true), param("sequenceId")],
      request: (a) => salesforgeApi("POST", `/workspaces/${encStr(a.workspaceId)}/integrations/webhooks`, {
        body: clean({ name: a.name, url: a.url, type: a.type, sequenceID: a.sequenceId }),
      }),
    }),
    cmd({
      name: "get_webhook",
      product: "salesforge",
      group: "webhooks",
      subcommand: "get",
      description: "Get webhook details by ID.",
      params: [param("workspaceId", "string", true), param("webhookId", "string", true)],
      request: (a) => salesforgeApi("GET", `/workspaces/${encStr(a.workspaceId)}/integrations/webhooks/${encStr(a.webhookId)}`),
    }),

    // Salesforge: multichannel sequences
    cmd({
      name: "list_sequences",
      product: "salesforge",
      group: "sequences",
      subcommand: "list",
      description: "List multichannel sequences in a workspace.",
      params: [param("workspaceId", "string", true), ...pagingParams],
      request: (a) => salesforgeApi("GET", `/multichannel/workspaces/${encStr(a.workspaceId)}/sequences`, { query: pick(a, ["limit", "offset"]) }),
    }),
    cmd({
      name: "create_sequence",
      product: "salesforge",
      group: "sequences",
      subcommand: "create",
      description: "Create a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("name", "string", true), param("description"), param("timezone")],
      request: (a) => salesforgeApi("POST", `/multichannel/workspaces/${encStr(a.workspaceId)}/sequences`, { body: omit(a, ["workspaceId"]) }),
    }),
    cmd({
      name: "get_sequence",
      product: "salesforge",
      group: "sequences",
      subcommand: "get",
      description: "Get multichannel sequence details.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("GET", seqPath(a)),
    }),
    cmd({
      name: "update_sequence",
      product: "salesforge",
      group: "sequences",
      subcommand: "update",
      description: "Update a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("name"), param("description"), param("timezone")],
      request: (a) => salesforgeApi("PATCH", seqPath(a), { body: omit(a, ["workspaceId", "sequenceId"]) }),
    }),
    cmd({
      name: "delete_sequence",
      product: "salesforge",
      group: "sequences",
      subcommand: "delete",
      description: "Delete a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("DELETE", seqPath(a)),
    }),
    cmd({
      name: "launch_sequence",
      product: "salesforge",
      group: "sequences",
      subcommand: "launch",
      description: "Launch a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("PATCH", `${seqPath(a)}/launch`, { body: {} }),
    }),
    cmd({
      name: "set_sequence_status",
      product: "salesforge",
      group: "sequences",
      subcommand: "status",
      description: "Set sequence status to active or paused.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("status", "string", true)],
      request: (a) => salesforgeApi("PATCH", `${seqPath(a)}/status`, { body: pick(a, ["status"]) }),
    }),
    cmd({
      name: "get_sequence_schedule",
      product: "salesforge",
      group: "sequences",
      subcommand: "schedule",
      description: "Get sequence schedule.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("GET", `${seqPath(a)}/schedule`),
    }),
    cmd({
      name: "update_sequence_schedule",
      product: "salesforge",
      group: "sequences",
      subcommand: "update-schedule",
      description: "Update sequence schedule.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("timezone", "string", true), param("schedule", "object", true)],
      request: (a) => salesforgeApi("PUT", `${seqPath(a)}/schedule`, { body: pick(a, ["timezone", "schedule"]) }),
    }),
    cmd({
      name: "get_sequence_settings",
      product: "salesforge",
      group: "sequences",
      subcommand: "settings",
      description: "Get sequence settings.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("GET", `${seqPath(a)}/settings`),
    }),
    cmd({
      name: "update_sequence_settings",
      product: "salesforge",
      group: "sequences",
      subcommand: "update-settings",
      description: "Update sequence settings.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("settings", "object", true)],
      request: (a) => salesforgeApi("PATCH", `${seqPath(a)}/settings`, { body: a.settings }),
    }),
    cmd({
      name: "list_sequence_branches",
      product: "salesforge",
      group: "branches",
      subcommand: "list",
      description: "List branches in a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("GET", `${seqPath(a)}/branches`),
    }),
    cmd({
      name: "list_sequence_nodes",
      product: "salesforge",
      group: "nodes",
      subcommand: "list",
      description: "List nodes in a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("GET", `${seqPath(a)}/nodes`),
    }),
    cmd({
      name: "get_sequence_node",
      product: "salesforge",
      group: "nodes",
      subcommand: "get",
      description: "Get a sequence node.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("nodeId", "string", true)],
      request: (a) => salesforgeApi("GET", `${seqPath(a)}/nodes/${encStr(a.nodeId)}`),
    }),
    cmd({
      name: "create_action_node",
      product: "salesforge",
      group: "nodes",
      subcommand: "create-action",
      description: "Create an action node in a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("branchId", "number", true), param("actionId", "number", true), param("waitDays", "number"), param("variants", "array"), param("distributionStrategy")],
      request: (a) => salesforgeApi("POST", `${seqPath(a)}/nodes/actions`, { body: clean(pick(a, ["branchId", "actionId", "waitDays", "variants", "distributionStrategy"])) }),
    }),
    cmd({
      name: "update_action_node",
      product: "salesforge",
      group: "nodes",
      subcommand: "update-action",
      description: "Update an action node.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("nodeId", "string", true), param("wait_in_minutes", "number"), param("variants", "array"), param("distributionStrategy")],
      request: (a) => salesforgeApi("PATCH", `${seqPath(a)}/nodes/actions/${encStr(a.nodeId)}`, { body: clean(pick(a, ["wait_in_minutes", "variants", "distributionStrategy"])) }),
    }),
    cmd({
      name: "create_condition_node",
      product: "salesforge",
      group: "nodes",
      subcommand: "create-condition",
      description: "Create a condition node in a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("branchId", "number", true), param("conditionId", "number", true), param("minutesToWait", "number"), param("distributionStrategy")],
      request: (a) => salesforgeApi("POST", `${seqPath(a)}/nodes/conditions`, { body: clean(pick(a, ["branchId", "conditionId", "minutesToWait", "distributionStrategy"])) }),
    }),
    cmd({
      name: "delete_sequence_node",
      product: "salesforge",
      group: "nodes",
      subcommand: "delete",
      description: "Delete a sequence node.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("nodeId", "string", true)],
      request: (a) => salesforgeApi("DELETE", `${seqPath(a)}/nodes/${encStr(a.nodeId)}`),
    }),
    cmd({
      name: "list_action_types",
      product: "salesforge",
      group: "reference",
      subcommand: "actions",
      description: "List action types for sequence nodes.",
      request: () => salesforgeApi("GET", "/multichannel/actions"),
    }),
    cmd({
      name: "list_condition_types",
      product: "salesforge",
      group: "reference",
      subcommand: "conditions",
      description: "List condition types for sequence branching.",
      request: () => salesforgeApi("GET", "/multichannel/conditions"),
    }),
    cmd({
      name: "list_sender_profiles",
      product: "salesforge",
      group: "sender-profiles",
      subcommand: "list",
      description: "List sender profiles in a workspace.",
      params: [param("workspaceId", "string", true)],
      request: (a) => salesforgeApi("GET", senderProfilesPath(a)),
    }),
    cmd({
      name: "update_sender_profile",
      product: "salesforge",
      group: "sender-profiles",
      subcommand: "update",
      description: "Update a sender profile.",
      params: [param("workspaceId", "string", true), param("senderProfileId", "string", true), param("updates", "object", true)],
      request: (a) => salesforgeApi("PATCH", senderProfilesPath(a, "senderProfileId"), { body: a.updates }),
    }),
    cmd({
      name: "delete_sender_profile",
      product: "salesforge",
      group: "sender-profiles",
      subcommand: "delete",
      description: "Delete a sender profile.",
      params: [param("workspaceId", "string", true), param("senderProfileId", "string", true)],
      request: (a) => salesforgeApi("DELETE", senderProfilesPath(a, "senderProfileId")),
    }),
    cmd({
      name: "list_sequence_sender_profiles",
      product: "salesforge",
      group: "sender-profiles",
      subcommand: "sequence-list",
      description: "List sender profiles assigned to a sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true)],
      request: (a) => salesforgeApi("GET", `${seqPath(a)}/sender-profiles`),
    }),
    cmd({
      name: "assign_sender_profiles_to_sequence",
      product: "salesforge",
      group: "sender-profiles",
      subcommand: "assign",
      description: "Assign sender profiles to a sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("senderProfileIds", "array", true)],
      request: (a) => salesforgeApi("POST", `${seqPath(a)}/sender-profiles`, { body: pick(a, ["senderProfileIds"]) }),
    }),
    cmd({
      name: "remove_sender_profiles_from_sequence",
      product: "salesforge",
      group: "sender-profiles",
      subcommand: "remove",
      description: "Remove sender profiles from a sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("senderProfileIds", "array", true)],
      request: (a) => salesforgeApi("POST", `${seqPath(a)}/sender-profiles/remove`, { body: pick(a, ["senderProfileIds"]) }),
    }),
    cmd({
      name: "enroll_contacts",
      product: "salesforge",
      group: "enrollments",
      subcommand: "create",
      description: "Enroll contacts into a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("filters", "object", true), param("limit", "number")],
      request: (a) => salesforgeApi("POST", `${seqPath(a)}/enrollments`, { body: clean(pick(a, ["filters", "limit"])) }),
    }),
    cmd({
      name: "remove_enrollments",
      product: "salesforge",
      group: "enrollments",
      subcommand: "remove",
      description: "Remove contacts from a multichannel sequence.",
      params: [param("workspaceId", "string", true), param("sequenceId", "string", true), param("filters", "object", true)],
      request: (a) => salesforgeApi("POST", `${seqPath(a)}/enrollments/remove`, { body: pick(a, ["filters"]) }),
    }),
    cmd({
      name: "start_email_validation",
      product: "salesforge",
      group: "validations",
      subcommand: "start",
      description: "Start an email validation run.",
      params: [param("workspaceId", "string", true), param("filters", "object")],
      request: (a) => salesforgeApi("POST", `/multichannel/workspaces/${encStr(a.workspaceId)}/validations`, { body: a.filters ? { filters: a.filters } : {} }),
    }),
    cmd({
      name: "get_validation_results",
      product: "salesforge",
      group: "validations",
      subcommand: "results",
      description: "Get email validation run results.",
      params: [param("workspaceId", "string", true), param("runId", "string", true)],
      request: (a) => salesforgeApi("GET", `/multichannel/workspaces/${encStr(a.workspaceId)}/validations/${encStr(a.runId)}/results`),
    }),
  ];
}

function seqPath(args: ReqArgs): string {
  return `/multichannel/workspaces/${encStr(args.workspaceId)}/sequences/${encStr(args.sequenceId)}`;
}

function senderProfilesPath(args: ReqArgs, idKey?: string): string {
  const base = `/multichannel/workspaces/${encStr(args.workspaceId)}/sender-profiles`;
  return idKey ? `${base}/${encStr(args[idKey])}` : base;
}
