import type { CommandDefinition, ProductId } from "../../types.js";
import { api, cmd, encStr, omit, param, pick, simpleProductCommands } from "../common.js";

export function primeforgeCommands(): CommandDefinition[] {
  const product: ProductId = "primeforge";
  return [
    ...simpleProductCommands(product),
    cmd({ name: "primeforge_get_workspace", product, group: "workspaces", subcommand: "get", description: "Get a Primeforge workspace.", params: [param("id", "string", true)], request: (a) => api(product, "GET", `/workspaces/${encStr(a.id)}`) }),
    cmd({ name: "primeforge_delete_workspace", product, group: "workspaces", subcommand: "delete", description: "Delete a Primeforge workspace.", params: [param("id", "string", true)], request: (a) => api(product, "DELETE", `/workspaces/${encStr(a.id)}`) }),
    cmd({ name: "primeforge_set_domain_forwarding", product, group: "workspaces", subcommand: "set-domain-forwarding", description: "Set domain forwarding for a Primeforge workspace.", params: [param("workspaceId", "string", true), param("forwardToDomain", "string", true)], request: (a) => api(product, "POST", `/workspaces/${encStr(a.workspaceId)}/domains/forwarding`, { body: pick(a, ["forwardToDomain"]) }) }),
    cmd({ name: "primeforge_export_mailboxes", product, group: "workspaces", subcommand: "export-mailboxes", description: "Export Primeforge mailboxes.", params: [param("workspaceId", "string", true), param("exportType", "string", true), param("search"), param("includedIds", "array"), param("excludedIds", "array")], request: (a) => api(product, "POST", `/workspaces/${encStr(a.workspaceId)}/exports`, { body: omit(a, ["workspaceId"]) }) }),
    cmd({ name: "primeforge_export_to_salesforge", product, group: "workspaces", subcommand: "export-to-salesforge", description: "Export Primeforge mailboxes to Salesforge.", params: [param("workspaceId", "string", true), param("exportType", "string", true), param("includedIds", "array"), param("excludedIds", "array")], request: (a) => api(product, "POST", `/workspaces/${encStr(a.workspaceId)}/exports/salesforge`, { body: omit(a, ["workspaceId"]) }) }),
    cmd({ name: "primeforge_list_domains", product, group: "domains", subcommand: "list", description: "List Primeforge domains.", params: [param("workspaceId")], request: (a) => api(product, "GET", "/domains", { query: pick(a, ["workspaceId"]) }) }),
    cmd({ name: "primeforge_get_domain", product, group: "domains", subcommand: "get", description: "Get a Primeforge domain.", params: [param("id", "string", true)], request: (a) => api(product, "GET", `/domains/${encStr(a.id)}`) }),
    cmd({ name: "primeforge_search_domains", product, group: "domains", subcommand: "search", description: "Search available Primeforge domains.", params: [param("domain", "string", true), param("check_google_workspace", "boolean"), param("check_ms365_workspace", "boolean")], request: (a) => api(product, "GET", "/domains/search-available", { query: pick(a, ["domain", "check_google_workspace", "check_ms365_workspace"]) }) }),
    cmd({ name: "primeforge_buy_domains", product, group: "domains", subcommand: "buy", description: "Purchase Primeforge domains.", params: [param("body", "object", true)], request: (a) => api(product, "POST", "/domains", { body: a.body }) }),
    cmd({ name: "primeforge_delete_domain", product, group: "domains", subcommand: "delete", description: "Delete a Primeforge domain.", params: [param("id", "string", true)], request: (a) => api(product, "DELETE", `/domains/${encStr(a.id)}`) }),
    cmd({ name: "primeforge_get_domain_dns", product, group: "domains", subcommand: "dns", description: "Get Primeforge domain DNS records.", params: [param("domainId", "string", true)], request: (a) => api(product, "GET", `/domains/${encStr(a.domainId)}/dns`) }),
    cmd({ name: "primeforge_bulk_dns_update", product, group: "domains", subcommand: "bulk-dns", description: "Bulk update Primeforge DNS records.", params: [param("domains", "array", true), param("dmarcEmail"), param("forwardToDomain")], request: (a) => api(product, "PUT", "/domains/bulk-dns", { body: a }) }),
    cmd({ name: "primeforge_create_mailboxes_for_domain", product, group: "domains", subcommand: "create-mailboxes", description: "Create mailboxes for a Primeforge domain.", params: [param("domainId", "string", true), param("workspaceId", "string", true), param("mailboxes", "array", true)], request: (a) => api(product, "POST", `/domains/${encStr(a.domainId)}/mailboxes`, { body: pick(a, ["workspaceId", "mailboxes"]) }) }),
    cmd({ name: "primeforge_list_mailboxes", product, group: "mailboxes", subcommand: "list", description: "List Primeforge mailboxes.", params: [param("workspaceId")], request: (a) => api(product, "GET", "/mailboxes", { query: pick(a, ["workspaceId"]) }) }),
    cmd({ name: "primeforge_get_mailbox", product, group: "mailboxes", subcommand: "get", description: "Get a Primeforge mailbox.", params: [param("id", "string", true)], request: (a) => api(product, "GET", `/mailboxes/${encStr(a.id)}`) }),
    cmd({ name: "primeforge_update_mailbox", product, group: "mailboxes", subcommand: "update", description: "Update a Primeforge mailbox.", params: [param("id", "string", true), param("firstName"), param("lastName"), param("signature"), param("forwardingEmail"), param("profilePictureUrl")], request: (a) => api(product, "PATCH", `/mailboxes/${encStr(a.id)}`, { body: omit(a, ["id"]) }) }),
    cmd({ name: "primeforge_delete_mailbox", product, group: "mailboxes", subcommand: "delete", description: "Delete a Primeforge mailbox.", params: [param("id", "string", true)], request: (a) => api(product, "DELETE", `/mailboxes/${encStr(a.id)}`) }),
    cmd({ name: "primeforge_list_prewarmed_mailboxes", product, group: "mailboxes", subcommand: "prewarmed", description: "List pre-warmed Primeforge mailboxes.", request: () => api(product, "GET", "/mailboxes/pre-warmed") }),
    cmd({ name: "primeforge_purchase_prewarmed_mailboxes", product, group: "mailboxes", subcommand: "purchase-prewarmed", description: "Purchase pre-warmed Primeforge mailboxes.", params: [param("body", "object", true)], request: (a) => api(product, "POST", "/mailboxes/pre-warmed", { body: a.body }) }),
  ];
}
