import type { CommandDefinition } from "../../types.js";
import { productEndpoint } from "../suite-endpoint.js";

export function infraforgeCommands(): CommandDefinition[] {
  return [
    productEndpoint("infraforge", "infraforge_list_workspaces", "workspaces", "list", "GET", "/workspaces"),
    productEndpoint("infraforge", "infraforge_create_workspace", "workspaces", "create", "POST", "/workspaces", {"required":["name"]}),
    productEndpoint("infraforge", "infraforge_update_workspace", "workspaces", "update", "PATCH", "/workspaces/{workspaceID}", {"required":["workspaceID"]}),
    productEndpoint("infraforge", "infraforge_delete_workspace", "workspaces", "delete", "DELETE", "/workspaces/{workspaceID}", {"required":["workspaceID"]}),
    productEndpoint("infraforge", "infraforge_export_mailboxes", "workspaces", "export-mailboxes", "POST", "/workspaces/{workspaceID}/mailboxes/export", {"bodyKey":"body","required":["workspaceID","body"]}),
    productEndpoint("infraforge", "infraforge_export_to_salesforge", "workspaces", "export-to-salesforge", "POST", "/mailboxes/export-to-salesforge", {"bodyKey":"body","required":["body"]}),
    productEndpoint("infraforge", "infraforge_check_domain_availability", "domains", "check", "GET", "/check-domain-availability", {"required":["domain"]}),
    productEndpoint("infraforge", "infraforge_check_domain_availability_bulk", "domains", "check-bulk", "POST", "/check-domain-availability-bulk", {"required":["domains"]}),
    productEndpoint("infraforge", "infraforge_list_domains", "domains", "list", "GET", "/domains"),
    productEndpoint("infraforge", "infraforge_purchase_domains", "domains", "purchase", "POST", "/domains", {"bodyKey":"body","required":["body"]}),
    productEndpoint("infraforge", "infraforge_get_domain_dns", "domains", "dns", "GET", "/domains/{domainID}/dns", {"required":["domainID"]}),
    productEndpoint("infraforge", "infraforge_update_domain_dns", "domains", "update-dns", "PUT", "/domains/{domainID}/dns", {"required":["domainID","records"]}),
    productEndpoint("infraforge", "infraforge_bulk_dns_update", "domains", "bulk-dns", "PUT", "/domains/bulk-dns", {"required":["domains"]}),
    productEndpoint("infraforge", "infraforge_get_alternative_domains", "domains", "alternatives", "POST", "/domains/alternative-domains", {"bodyKey":"body","required":["body"]}),
    productEndpoint("infraforge", "infraforge_enable_autorenew", "domains", "enable-autorenew", "PUT", "/domains/{domainID}/enable-autorenew", {"required":["domainID"]}),
    productEndpoint("infraforge", "infraforge_disable_autorenew", "domains", "disable-autorenew", "PUT", "/domains/{domainID}/disable-autorenew", {"required":["domainID"]}),
    productEndpoint("infraforge", "infraforge_list_mailboxes", "mailboxes", "list", "GET", "/mailboxes"),
    productEndpoint("infraforge", "infraforge_get_mailbox", "mailboxes", "get", "GET", "/mailboxes/{mailboxID}", {"required":["mailboxID"]}),
    productEndpoint("infraforge", "infraforge_update_mailbox", "mailboxes", "update", "PATCH", "/mailboxes/{mailboxID}", {"required":["mailboxID"]}),
    productEndpoint("infraforge", "infraforge_purchase_mailboxes", "mailboxes", "purchase", "POST", "/mailboxes", {"bodyKey":"body","required":["body"]}),
    productEndpoint("infraforge", "infraforge_delete_mailbox", "mailboxes", "delete", "DELETE", "/mailboxes/{mailboxID}", {"required":["mailboxID"]}),
    productEndpoint("infraforge", "infraforge_generate_mailboxes", "mailboxes", "generate", "POST", "/mailboxes/generate", {"bodyKey":"body","required":["body"]}),
    productEndpoint("infraforge", "infraforge_bulk_forward_mailboxes", "mailboxes", "bulk-forward", "POST", "/mailboxes/bulk-forward", {"bodyKey":"body","required":["body"]}),
    productEndpoint("infraforge", "infraforge_get_credit_balance", "credits", "balance", "GET", "/credits/balance"),
    productEndpoint("infraforge", "infraforge_create_credit_balance", "credits", "create", "POST", "/credits/balance", {"required":["amount","isEnabled","topupThreshold"]}),
    productEndpoint("infraforge", "infraforge_update_credit_balance", "credits", "update", "PATCH", "/credits/balance"),
    productEndpoint("infraforge", "infraforge_adjust_topup_amount", "mailboxes", "adjust-topup", "POST", "/adjust-mailbox-topup-amount"),
    productEndpoint("infraforge", "infraforge_bulk_disable_autorenew", "domains", "bulk-disable-autorenew", "POST", "/domains/bulk-disable-autorenew"),
    productEndpoint("infraforge", "infraforge_bulk_enable_autorenew", "domains", "bulk-enable-autorenew", "POST", "/domains/bulk-enable-autorenew"),
    productEndpoint("infraforge", "infraforge_update_domain_forwards", "domains", "update-forwards", "PATCH", "/domains/forwards", {"bodyKey":"forwards"}),
    productEndpoint("infraforge", "infraforge_purchase_domain_masking", "domains", "purchase-masking", "POST", "/domains/masking"),
    productEndpoint("infraforge", "infraforge_purchase_prewarmed_domains", "domains", "purchase-prewarmed", "POST", "/domains/pre-warmed"),
    productEndpoint("infraforge", "infraforge_transfer_domains", "domains", "transfer", "POST", "/domains/transfer"),
    productEndpoint("infraforge", "infraforge_get_domain_transfer_ns_info", "domains", "transfer-ns-info", "GET", "/domains/transfer-ns-info"),
    productEndpoint("infraforge", "infraforge_delete_domain_masking", "domains", "delete-masking", "DELETE", "/domains/{domainID}/masking"),
    productEndpoint("infraforge", "infraforge_get_domain_renewal_price", "domains", "renewal-price", "GET", "/domains/{domainID}/renewal-price"),
    productEndpoint("infraforge", "infraforge_transfer_domain_out", "domains", "transfer-out", "POST", "/domains/{domainID}/transfer-out"),
    productEndpoint("infraforge", "infraforge_list_prewarmed_domains", "domains", "prewarmed", "GET", "/mailboxes/pre-warmed"),
    productEndpoint("infraforge", "infraforge_get_postal_code_details", "reference", "postal-code-details", "GET", "/postal-code-details"),
    productEndpoint("infraforge", "infraforge_transfer_domains_to_workspace", "workspaces", "transfer-domains", "POST", "/workspaces/{workspaceID}/domains/transfer-to-workspace"),
    productEndpoint("infraforge", "infraforge_get_core_domains", "workspaces", "core-domains", "GET", "/workspaces/domains/core"),
    productEndpoint("infraforge", "infraforge_update_ip_core_domain", "workspaces", "update-core-domain", "POST", "/workspaces/domains/core"),
    productEndpoint("infraforge", "infraforge_delete_workspace_ip", "workspaces", "delete-ip", "DELETE", "/workspaces/ips/{ip}"),
    productEndpoint("infraforge", "infraforge_get_eligible_ips", "workspaces", "eligible-ips", "GET", "/workspaces/{workspaceID}/eligible-ips"),
    productEndpoint("infraforge", "infraforge_adjust_domain_max_mailboxes", "domains", "max-mailboxes", "PATCH", "/domains/{domainID}/max-mailboxes"),
  ];
}
