import type { CommandDefinition, ProductId } from "../../types.js";
import { api, cmd, encStr, omit, param, pick, simpleProductCommands } from "../common.js";

export function mailforgeCommands(): CommandDefinition[] {
  const product: ProductId = "mailforge";
  return [
    ...simpleProductCommands(product),
    cmd({ name: "mailforge_update_workspace", product, group: "workspaces", subcommand: "update", description: "Update a Mailforge workspace.", params: [param("workspaceID", "string", true), param("name", "string", true)], request: (a) => api(product, "PATCH", `/workspaces/${encStr(a.workspaceID)}`, { body: pick(a, ["name"]) }) }),
    cmd({ name: "mailforge_delete_workspace", product, group: "workspaces", subcommand: "delete", description: "Delete a Mailforge workspace.", params: [param("workspaceID", "string", true)], request: (a) => api(product, "DELETE", `/workspaces/${encStr(a.workspaceID)}`) }),
    cmd({ name: "mailforge_list_mailboxes", product, group: "mailboxes", subcommand: "list", description: "List Mailforge mailboxes.", request: () => api(product, "GET", "/mailboxes") }),
    cmd({ name: "mailforge_get_mailbox", product, group: "mailboxes", subcommand: "get", description: "Get a Mailforge mailbox.", params: [param("mailboxID", "string", true)], request: (a) => api(product, "GET", `/mailboxes/${encStr(a.mailboxID)}`) }),
    cmd({ name: "mailforge_purchase_mailboxes", product, group: "mailboxes", subcommand: "purchase", description: "Purchase Mailforge mailboxes.", params: [param("mailboxes", "array", true)], request: (a) => api(product, "POST", "/mailboxes", { body: pick(a, ["mailboxes"]) }) }),
    cmd({ name: "mailforge_update_mailbox", product, group: "mailboxes", subcommand: "update", description: "Update a Mailforge mailbox.", params: [param("mailboxID", "string", true), param("firstName"), param("lastName"), param("password"), param("signature"), param("forwardingEmail")], request: (a) => api(product, "PATCH", `/mailboxes/${encStr(a.mailboxID)}`, { body: omit(a, ["mailboxID"]) }) }),
    cmd({ name: "mailforge_delete_mailbox", product, group: "mailboxes", subcommand: "delete", description: "Delete a Mailforge mailbox.", params: [param("mailboxID", "string", true)], request: (a) => api(product, "DELETE", `/mailboxes/${encStr(a.mailboxID)}`) }),
    cmd({ name: "mailforge_bulk_forward_mailboxes", product, group: "mailboxes", subcommand: "bulk-forward", description: "Bulk set Mailforge mailbox forwarding.", params: [param("forwardingEmail", "string", true), param("search"), param("includedIds", "array"), param("excludedIds", "array")], request: (a) => api(product, "POST", "/mailboxes/bulk-forward", { body: a }) }),
    cmd({ name: "mailforge_adjust_topup_amount", product, group: "mailboxes", subcommand: "adjust-topup", description: "Adjust Mailforge mailbox top-up amount.", params: [param("amount", "number", true)], request: (a) => api(product, "POST", "/adjust-mailbox-topup-amount", { body: pick(a, ["amount"]) }) }),
    cmd({ name: "mailforge_list_domains", product, group: "domains", subcommand: "list", description: "List Mailforge domains.", params: [param("status")], request: (a) => api(product, "GET", "/domains", { query: pick(a, ["status"]) }) }),
    cmd({ name: "mailforge_purchase_domains", product, group: "domains", subcommand: "purchase", description: "Purchase Mailforge domains.", params: [param("domains", "array", true), param("workspaceId", "string", true), param("contactDetails", "object", true)], request: (a) => api(product, "POST", "/domains", { body: pick(a, ["domains", "workspaceId", "contactDetails"]) }) }),
    cmd({ name: "mailforge_check_domain_availability", product, group: "domains", subcommand: "check", description: "Check Mailforge domain availability.", params: [param("domain", "string", true)], request: (a) => api(product, "GET", "/check-domain-availability", { query: pick(a, ["domain"]) }) }),
    cmd({ name: "mailforge_check_domain_availability_bulk", product, group: "domains", subcommand: "check-bulk", description: "Check Mailforge domain availability in bulk.", params: [param("domains", "array", true)], request: (a) => api(product, "POST", "/check-domain-availability-bulk", { body: pick(a, ["domains"]) }) }),
    cmd({ name: "mailforge_transfer_domains", product, group: "domains", subcommand: "transfer", description: "Transfer domains into Mailforge.", params: [param("domains", "array", true), param("workspaceId", "string", true), param("dmarcEmail"), param("forwardToDomain")], request: (a) => api(product, "POST", "/domains/transfer", { body: a }) }),
    cmd({ name: "mailforge_get_domain_dns", product, group: "domains", subcommand: "dns", description: "Get Mailforge domain DNS.", params: [param("domainID", "string", true)], request: (a) => api(product, "GET", `/domains/${encStr(a.domainID)}/dns`) }),
    cmd({ name: "mailforge_update_domain_dns", product, group: "domains", subcommand: "update-dns", description: "Update Mailforge domain DNS.", params: [param("domainID", "string", true), param("records", "array", true)], request: (a) => api(product, "PUT", `/domains/${encStr(a.domainID)}/dns`, { body: pick(a, ["records"]) }) }),
    cmd({ name: "mailforge_bulk_dns_update", product, group: "domains", subcommand: "bulk-dns", description: "Bulk update Mailforge DNS.", params: [param("domains", "array", true), param("dmarcEmail"), param("dmarcPolicy"), param("forwardToDomain"), param("removeENOMRecords", "boolean")], request: (a) => api(product, "PUT", "/domains/bulk-dns", { body: a }) }),
    cmd({ name: "mailforge_enable_autorenew", product, group: "domains", subcommand: "enable-autorenew", description: "Enable Mailforge domain auto-renewal.", params: [param("domainID", "string", true)], request: (a) => api(product, "PUT", `/domains/${encStr(a.domainID)}/enable-autorenew`, { body: {} }) }),
    cmd({ name: "mailforge_disable_autorenew", product, group: "domains", subcommand: "disable-autorenew", description: "Disable Mailforge domain auto-renewal.", params: [param("domainID", "string", true)], request: (a) => api(product, "PUT", `/domains/${encStr(a.domainID)}/disable-autorenew`, { body: {} }) }),
    cmd({ name: "mailforge_bulk_enable_autorenew", product, group: "domains", subcommand: "bulk-enable-autorenew", description: "Enable auto-renewal for multiple domains.", params: [param("domainIds", "array", true)], request: (a) => api(product, "POST", "/domains/bulk-enable-autorenew", { body: pick(a, ["domainIds"]) }) }),
    cmd({ name: "mailforge_bulk_disable_autorenew", product, group: "domains", subcommand: "bulk-disable-autorenew", description: "Disable auto-renewal for multiple domains.", params: [param("domainIds", "array", true)], request: (a) => api(product, "POST", "/domains/bulk-disable-autorenew", { body: pick(a, ["domainIds"]) }) }),
    cmd({ name: "mailforge_update_domain_forwards", product, group: "domains", subcommand: "update-forwards", description: "Update Mailforge domain forwards.", params: [param("forwards", "array", true)], request: (a) => api(product, "PATCH", "/domains/forwards", { body: a.forwards }) }),
    cmd({ name: "mailforge_purchase_domain_masking", product, group: "domains", subcommand: "purchase-masking", description: "Purchase domain masking.", params: [param("domainIds", "array", true), param("purchaseMasking", "boolean", true), param("isYearly", "boolean")], request: (a) => api(product, "POST", "/domains/masking", { body: a }) }),
    cmd({ name: "mailforge_delete_domain_masking", product, group: "domains", subcommand: "delete-masking", description: "Delete domain masking.", params: [param("domainID", "string", true)], request: (a) => api(product, "DELETE", `/domains/${encStr(a.domainID)}/masking`) }),
  ];
}
